/* Golden test: BEP52 hash request / hashes / hash reject codec.
 *
 * Reads committed vectors from test/vectors/bep52/hash_* (generated by
 * test/scripts/bep52_hash_msgs.py — never hardcoded here) and asserts:
 *   - framed parse + byte-exact round-trip for every vector,
 *   - field values against the .meta.json sidecars,
 *   - ntx_hash_req_constraints_ok() verdicts both ways (the two illegal
 *     vectors are framing-legal: the parser MUST accept them, the
 *     constraint check MUST reject them).
 * Plus payload-level round-trips, builder cap/validation and negatives.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#include "util.h"
#include "golden_meta.h"

#include "../src/core/ntx_hash_msg.c"

static int g_fail;

static void expect(const char *name, int ok) {
    if (ok) printf("PASS %s\n", name);
    else { printf("FAIL %s\n", name); g_fail = 1; }
}

static int hex_to(const char *hex, uint8_t *out, size_t n) {
    if (strlen(hex) != n * 2) return 0;
    for (size_t i = 0; i < n; i++) {
        unsigned v;
        if (sscanf(hex + 2 * i, "%2x", &v) != 1) return 0;
        out[i] = (uint8_t)v;
    }
    return 1;
}

static uint32_t rd32(const uint8_t *p) {
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) |
           ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static void tag(char *buf, size_t cap, const char *stem, const char *what) {
    snprintf(buf, cap, "%s:%s", stem, what);
}

static int load_meta(const char *stem, gm *root) {
    char path[256];
    snprintf(path, sizeof path, "test/vectors/bep52/%s.meta.json", stem);
    size_t mn;
    uint8_t *meta = read_file(path, &mn);
    int ok = gm_parse((const char *)meta, mn, root) == 0;
    free(meta);
    return ok;
}

/* Compare parsed header against meta.fields; returns 1 when all match. */
static int fields_match(const gm *root, const ntx_hash_req *r) {
    const gm *f = gm_get(root, "fields");
    if (!f || f->t != GM_OBJ) return 0;
    const char *root_hex = NULL;
    int64_t bl, ix, ln, pl;
    if (gm_str(gm_get(f, "pieces_root"), &root_hex) != 0) return 0;
    if (gm_num(gm_get(f, "base_layer"), &bl) != 0) return 0;
    if (gm_num(gm_get(f, "index"), &ix) != 0) return 0;
    if (gm_num(gm_get(f, "length"), &ln) != 0) return 0;
    if (gm_num(gm_get(f, "proof_layers"), &pl) != 0) return 0;
    uint8_t expect_root[32];
    if (!hex_to(root_hex, expect_root, 32)) return 0;
    return memcmp(r->pieces_root, expect_root, 32) == 0 &&
           r->base_layer == (uint32_t)bl && r->index == (uint32_t)ix &&
           r->length == (uint32_t)ln && r->proof_layers == (uint32_t)pl;
}

/* Common sidecar checks: msg.id, framing sizes vs the raw bytes. */
static void check_framing(const char *stem, const gm *root, uint8_t want_id,
                          const uint8_t *bin, size_t n) {
    char t[256];
    const gm *msg = gm_get(root, "msg");
    const gm *fr = gm_get(root, "framing");
    int64_t mid = -1, pb = -1, tb = -1;
    if (msg) gm_num(gm_get(msg, "id"), &mid);
    if (fr) {
        gm_num(gm_get(fr, "payload_bytes"), &pb);
        gm_num(gm_get(fr, "total_bytes"), &tb);
    }
    tag(t, sizeof t, stem, "meta-msg-id");
    expect(t, mid == (int64_t)want_id && bin[4] == want_id);
    tag(t, sizeof t, stem, "meta-framing");
    expect(t, tb >= 5 && n == (size_t)tb && pb >= 1 &&
              rd32(bin) == (uint32_t)(pb + 1) && n == (size_t)pb + 5);
}

/* Parse a request/reject vector (framed), round-trip via builder,
 * constraints_ok verdict per meta.legality. */
static void run_req_vector(const char *stem, uint8_t id,
                           int (*parse)(const uint8_t *, size_t, ntx_hash_req *),
                           size_t (*build)(uint8_t *, size_t, const ntx_hash_req *)) {
    char t[256];
    gm root;
    if (!load_meta(stem, &root)) { expect("meta-parse", 0); return; }
    const gm *fr = gm_get(&root, "framing");
    const gm *leg = gm_get(&root, "legality");
    const char *legality = NULL;
    if (leg) gm_str(leg, &legality);
    int64_t tb = 0;
    if (fr) gm_num(gm_get(fr, "total_bytes"), &tb);

    char path[256];
    snprintf(path, sizeof path, "test/vectors/bep52/%s.bin", stem);
    size_t n = 0;
    uint8_t *bin = read_file(path, &n);

    check_framing(stem, &root, id, bin, n);

    ntx_hash_req r;
    memset(&r, 0xAA, sizeof r);
    tag(t, sizeof t, stem, "parse");
    int prc = parse(bin, n, &r);
    expect(t, prc == 0);
    if (prc != 0) { free(bin); gm_free(&root); return; }

    tag(t, sizeof t, stem, "fields");
    expect(t, fields_match(&root, &r));

    uint8_t out[64];
    memset(out, 0x5A, sizeof out);
    tag(t, sizeof t, stem, "roundtrip-framed");
    size_t w = build(out, sizeof out, &r);
    expect(t, w == n && (size_t)tb == n && memcmp(out, bin, n) == 0);

    uint8_t pl[NTX_HASH_REQ_PAYLOAD];
    memset(pl, 0x5A, sizeof pl);
    tag(t, sizeof t, stem, "roundtrip-payload");
    ntx_hash_req r2;
    expect(t, ntx_hash_req_write(pl, sizeof pl, &r) == NTX_HASH_REQ_PAYLOAD &&
              memcmp(pl, bin + 5, NTX_HASH_REQ_PAYLOAD) == 0 &&
              ntx_hash_req_parse(pl, NTX_HASH_REQ_PAYLOAD, &r2) == 0 &&
              memcmp(&r2, &r, sizeof r2) == 0);

    tag(t, sizeof t, stem, "constraints");
    int want = legality && strcmp(legality, "legal") == 0;
    expect(t, ntx_hash_req_constraints_ok(&r) == (want ? 1 : 0));

    free(bin);
    gm_free(&root);
}

static void run_hashes_vector(void) {
    const char *stem = "hashes_omitted_proof_layers";
    char t[256];
    gm root;
    if (!load_meta(stem, &root)) { expect("meta-parse", 0); return; }
    const gm *fr = gm_get(&root, "framing");
    const gm *leg = gm_get(&root, "legality");
    const char *legality = NULL;
    if (leg) gm_str(leg, &legality);
    int64_t pb = 0;
    if (fr) gm_num(gm_get(fr, "payload_bytes"), &pb);

    char path[256];
    snprintf(path, sizeof path, "test/vectors/bep52/%s.bin", stem);
    size_t n = 0;
    uint8_t *bin = read_file(path, &n);

    check_framing(stem, &root, NTX_MSG_HASHES, bin, n);

    ntx_hash_req hdr;
    const uint8_t *hashes = NULL;
    size_t hn = 0;
    tag(t, sizeof t, stem, "parse");
    int prc = ntx_hash_msg_parse_hashes(bin, n, &hdr, &hashes, &hn);
    expect(t, prc == 0);
    if (prc != 0) { free(bin); gm_free(&root); return; }

    tag(t, sizeof t, stem, "fields");
    expect(t, fields_match(&root, &hdr));

    /* hashes blob vs meta.fields.hashes {bytes,hex} */
    const gm *fh = gm_get(gm_get(&root, "fields"), "hashes");
    const char *hx = NULL;
    int64_t hbytes = -1;
    if (fh) {
        gm_str(gm_get(fh, "hex"), &hx);
        gm_num(gm_get(fh, "bytes"), &hbytes);
    }
    tag(t, sizeof t, stem, "hashes-blob");
    expect(t, hn == (size_t)hbytes && hn == 192 && hx &&
              memcmp(hashes, bin + 5 + NTX_HASH_REQ_PAYLOAD, hn) == 0);
    uint8_t hexp[192];
    tag(t, sizeof t, stem, "hashes-hex");
    expect(t, hx && hex_to(hx, hexp, 192) && memcmp(hashes, hexp, 192) == 0);

    tag(t, sizeof t, stem, "payload-len");
    expect(t, ntx_hash_msg_hashes_payload_len(&hdr, hn) == (size_t)pb &&
              (size_t)pb == NTX_HASH_REQ_PAYLOAD + hn);

    uint8_t out[256];
    memset(out, 0x5A, sizeof out);
    tag(t, sizeof t, stem, "roundtrip-framed");
    size_t w = ntx_hash_msg_build_hashes(out, sizeof out, &hdr, hashes, hn);
    expect(t, w == n && memcmp(out, bin, n) == 0);

    uint8_t pl[256];
    ntx_hash_req hdr2;
    const uint8_t *h2 = NULL;
    size_t hn2 = 0;
    tag(t, sizeof t, stem, "roundtrip-payload");
    expect(t, ntx_hash_hashes_write(pl, sizeof pl, &hdr, hashes, hn) == hn + NTX_HASH_REQ_PAYLOAD &&
              memcmp(pl, bin + 5, (size_t)pb) == 0 &&
              ntx_hash_hashes_parse(pl, (size_t)pb, &hdr2, &h2, &hn2) == 0 &&
              memcmp(&hdr2, &hdr, sizeof hdr2) == 0 && hn2 == hn &&
              h2 && memcmp(h2, hashes, hn) == 0);

    tag(t, sizeof t, stem, "constraints");
    int want = legality && strcmp(legality, "legal") == 0;
    expect(t, ntx_hash_req_constraints_ok(&hdr) == (want ? 1 : 0));

    free(bin);
    gm_free(&root);
}

/* reject payload must be identical to the leaf request payload (BEP52) */
static void run_reject_vs_leaf(void) {
    size_t ln = 0, rn = 0;
    uint8_t *leaf = read_file("test/vectors/bep52/hash_request_leaf.bin", &ln);
    uint8_t *rej = read_file("test/vectors/bep52/hash_reject.bin", &rn);
    expect("hash_reject:payload-equals-leaf-request",
           ln == rn && ln == 53 && memcmp(leaf + 5, rej + 5, ln - 5) == 0);
    free(leaf);
    free(rej);
}

static void run_negatives(void) {
    size_t n = 0;
    uint8_t *bin = read_file("test/vectors/bep52/hash_request_leaf.bin", &n);
    ntx_hash_req r;

    expect("neg:parse-request-truncated",
           ntx_hash_msg_parse_request(bin, n - 1, &r) == -1);
    expect("neg:parse-request-short",
           ntx_hash_msg_parse_request(bin, 4, &r) == -1);
    uint8_t tmp[64];
    memcpy(tmp, bin, n);
    tmp[4] = NTX_MSG_HASHES;
    expect("neg:parse-request-wrong-id",
           ntx_hash_msg_parse_request(tmp, n, &r) == -1);
    memcpy(tmp, bin, n);
    tmp[3] = (uint8_t)(bin[3] + 1); /* bump length prefix -> != n - 4 */
    expect("neg:parse-request-len-mismatch",
           ntx_hash_msg_parse_request(tmp, n, &r) == -1);
    uint8_t keep[4] = {0, 0, 0, 0};
    expect("neg:parse-request-keepalive",
           ntx_hash_msg_parse_request(keep, 4, &r) == -1);
    expect("neg:build-request-cap",
           ntx_hash_msg_parse_request(bin, n, &r) == 0 &&
           ntx_hash_msg_build_request(tmp, 52, &r) == 0);
    expect("neg:build-request-null",
           ntx_hash_msg_build_request(tmp, sizeof tmp, NULL) == 0);
    expect("neg:req-parse-payload-size",
           ntx_hash_req_parse(bin + 5, NTX_HASH_REQ_PAYLOAD - 1, &r) == -1);
    free(bin);

    bin = read_file("test/vectors/bep52/hashes_omitted_proof_layers.bin", &n);
    ntx_hash_req hdr;
    const uint8_t *h = NULL;
    size_t hn = 0;
    expect("hashes:parse-ok-for-negative",
           ntx_hash_msg_parse_hashes(bin, n, &hdr, &h, &hn) == 0);
    expect("neg:parse-hashes-truncated",
           ntx_hash_msg_parse_hashes(bin, n - 1, &hdr, &h, &hn) == -1);
    uint8_t badpl[49];
    memcpy(badpl, bin + 5, sizeof badpl);
    expect("neg:hashes-parse-not-multiple-32",
           ntx_hash_hashes_parse(badpl, sizeof badpl, &hdr, &h, &hn) == -1);
    expect("neg:hashes-write-not-multiple-32",
           ntx_hash_hashes_write(badpl, sizeof badpl, &hdr, h, 33) == 0);
    expect("neg:build-hashes-not-multiple-32",
           ntx_hash_msg_build_hashes(badpl, sizeof badpl, &hdr, h, 33) == 0);
    expect("neg:build-hashes-cap",
           ntx_hash_msg_build_hashes(badpl, 244, &hdr, h, hn) == 0);
    /* fewer base hashes than the requested span (BEP52: response must carry
     * the base layer range) */
    expect("neg:hashes-payload-len-short-bases",
           ntx_hash_msg_hashes_payload_len(&hdr, 64) == 0);
    free(bin);

    /* payload-level empty hashes blob is framing-legal */
    ntx_hash_req e = { {0}, 0, 0, 2, 0 };
    uint8_t pl[64];
    ntx_hash_req eh;
    const uint8_t *ep = NULL;
    size_t en = 99;
    expect("payload:hashes-empty-blob",
           ntx_hash_hashes_write(pl, sizeof pl, &e, NULL, 0) == NTX_HASH_REQ_PAYLOAD &&
           ntx_hash_hashes_parse(pl, NTX_HASH_REQ_PAYLOAD, &eh, &ep, &en) == 0 &&
           ep == NULL && en == 0);
}

static void run_constraints_table(void) {
    ntx_hash_req r = { {0}, 0, 0, 0, 0 };
    struct { uint32_t index, length; int want; const char *name; } cases[] = {
        {0, 0, 0, "constraints:length-zero"},
        {0, 1, 0, "constraints:length-one"},
        {0, 3, 0, "constraints:length-non-pow2"},
        {1, 2, 0, "constraints:index-not-multiple"},
        {0, 2, 1, "constraints:length-two-ok"},
        {8, 4, 1, "constraints:index-multiple-ok"},
        {0, 512, 1, "constraints:length-512-ok"},
        {0, 1024, 1, "constraints:length-above-512-should-not-enforced"},
        {2, 4, 0, "constraints:index-2-len-4-reject"},
    };
    for (size_t i = 0; i < sizeof cases / sizeof cases[0]; i++) {
        r.index = cases[i].index;
        r.length = cases[i].length;
        expect(cases[i].name, ntx_hash_req_constraints_ok(&r) == cases[i].want);
    }
    expect("constraints:null", ntx_hash_req_constraints_ok(NULL) == 0);
}

int main(void) {
    run_req_vector("hash_request_leaf", NTX_MSG_HASH_REQUEST,
                   ntx_hash_msg_parse_request, ntx_hash_msg_build_request);
    run_req_vector("hash_request_piece_layer", NTX_MSG_HASH_REQUEST,
                   ntx_hash_msg_parse_request, ntx_hash_msg_build_request);
    run_req_vector("hash_request_illegal_length", NTX_MSG_HASH_REQUEST,
                   ntx_hash_msg_parse_request, ntx_hash_msg_build_request);
    run_req_vector("hash_request_illegal_index", NTX_MSG_HASH_REQUEST,
                   ntx_hash_msg_parse_request, ntx_hash_msg_build_request);
    run_req_vector("hash_reject", NTX_MSG_HASH_REJECT,
                   ntx_hash_msg_parse_reject, ntx_hash_msg_build_reject);
    run_hashes_vector();
    run_reject_vs_leaf();
    run_negatives();
    run_constraints_table();
    if (g_fail) {
        printf("FAILED\n");
        return 1;
    }
    printf("ALL PASS\n");
    return 0;
}
