/* SOCKS5 UDP ASSOCIATE framing (RFC1928 §7) for uTP egress.
 *
 * Self-contained TU: loads committed golden vectors generated by
 * test/scripts/socks_udp_frames.py, then runs a loopback SOCKS5 UDP relay stub
 * implemented in this test itself. The stub proves wire bytes and the relay
 * reply path (DATA -> packet callback, i.e. what ntx_utp_input would accept)
 * without sleeps. */
#include <arpa/inet.h>
#include <assert.h>
#include <errno.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#include "golden_meta.h"
#include "../src/net/ntx_addr.c"
#include "../src/net/ntx_proxy.c"
#include "../src/net/ntx_sock.c"
#include "../src/crypto/ntx_sha256.c"
#include "../src/ui/ntx_diag.c"

static int fails;

static void check(int cond, const char *name) {
    if (cond) printf("PASS %s\n", name);
    else { printf("FAIL %s\n", name); fails = 1; }
}

static uint8_t *read_file(const char *path, size_t *n) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }
    uint8_t *buf = malloc(sz > 0 ? (size_t)sz : 1);
    if (!buf) { fclose(f); return NULL; }
    size_t rd = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (rd != (size_t)sz) { free(buf); return NULL; }
    *n = (size_t)sz;
    return buf;
}

static int hexnib(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static long hexbytes(const char *hex, uint8_t *out, size_t cap) {
    size_t len = strlen(hex);
    if (len % 2 != 0) return -1;
    if (len / 2 > cap) return -1;
    for (size_t i = 0; i < len / 2; i++) {
        int hi = hexnib(hex[2 * i]), lo = hexnib(hex[2 * i + 1]);
        if (hi < 0 || lo < 0) return -1;
        out[i] = (uint8_t)((hi << 4) | lo);
    }
    return (long)(len / 2);
}

static int recv_all(int fd, uint8_t *buf, size_t n) {
    size_t got = 0;
    int iters = 0;
    while (got < n && iters++ < 2000) {
        ssize_t r = recv(fd, buf + got, n - got, 0);
        if (r > 0) {
            got += (size_t)r;
            continue;
        }
        if (r < 0 && (errno == EAGAIN || errno == EWOULDBLOCK)) {
            struct pollfd pf = {fd, POLLIN, 0};
            if (poll(&pf, 1, 100) <= 0) return -1;
            continue;
        }
        return -1;
    }
    return got == n ? 0 : -1;
}

/* ------------------------------------------------------------------ */
/* Golden vectors                                                      */
/* ------------------------------------------------------------------ */
static void test_codec_vectors(void) {
    size_t mn = 0;
    uint8_t *meta = read_file("test/vectors/socks/udp_associate_frames.meta.json", &mn);
    check(meta != NULL, "socks-meta-read");
    if (!meta) return;

    gm root;
    check(gm_parse((const char *)meta, mn, &root) == 0, "socks-meta-parse");
    if (root.t != GM_OBJ) { check(0, "socks-meta-obj"); free(meta); return; }

    const gm *bin = gm_get(&root, "bin");
    const gm *want_sha = gm_get(&root, "bin_sha256");
    const gm *cnt = gm_get(&root, "count");
    const gm *arr = gm_get(&root, "cases");
    int64_t ecnt = -1;
    check(bin && want_sha && cnt && gm_num(cnt, &ecnt) == 0 && arr &&
          arr->t == GM_ARR, "socks-meta-shape");
    if (!bin || !want_sha || !cnt || !arr || arr->t != GM_ARR) {
        free(meta);
        return;
    }

    size_t bn = 0;
    const char *binp = NULL;
    if (gm_str(bin, &binp) != 0 || !binp) {
        check(0, "socks-bin-name");
        free(meta);
        return;
    }
    uint8_t *blob = read_file(binp, &bn);
    check(blob != NULL, "socks-bin-read");
    if (!blob) { free(meta); return; }

    uint8_t dig[32];
    ntx_sha256(blob, bn, dig);
    char dighex[65];
    for (int i = 0; i < 32; i++) sprintf(dighex + 2 * i, "%02x", dig[i]);
    dighex[64] = 0;
    const char *ewant = NULL;
    check(gm_str(want_sha, &ewant) == 0 && strcmp(dighex, ewant) == 0,
          "socks-bin-sha256");

    check((int64_t)arr->ne == ecnt, "socks-case-count");

    for (size_t i = 0; i < arr->ne; i++) {
        const gm *c = arr->el[i];
        if (!c || c->t != GM_OBJ) { check(0, "socks-case-obj"); continue; }
        const char *name = "?", *type = "?", *expected = "?", *hex = "";
        const char *dst_hex = NULL, *data_hex = NULL;
        int64_t off = -1, len = -1, port = -1, atyp = -1;
        if (gm_str(gm_get(c, "name"), &name) != 0 ||
            gm_str(gm_get(c, "type"), &type) != 0 ||
            gm_str(gm_get(c, "expected"), &expected) != 0 ||
            gm_str(gm_get(c, "hex"), &hex) != 0 ||
            gm_num(gm_get(c, "off"), &off) != 0 ||
            gm_num(gm_get(c, "len"), &len) != 0) {
            check(0, "socks-case-fields");
            continue;
        }
        uint8_t expect[2048];
        long hn = hexbytes(hex, expect, sizeof expect);
        int ok = hn >= 0 && hn == len && off >= 0 &&
                 (size_t)off + (size_t)len <= bn &&
                 (len == 0 || memcmp(blob + off, expect, (size_t)len) == 0);
        char tname[160];
        snprintf(tname, sizeof tname, "socks-%s-integrity", name);
        check(ok, tname);

        if (strcmp(type, "decap") == 0) {
            ntx_addr dst;
            uint16_t dport = 0;
            const uint8_t *data = NULL;
            size_t data_len = 999;
            int rc = ntx_proxy_udp_decap(blob + off, (size_t)len, &dst, &dport,
                                        &data, &data_len);
            snprintf(tname, sizeof tname, "socks-%s=%s", name, expected);
            if (strcmp(expected, "reject") == 0) {
                const char *reason = "";
                gm_str(gm_get(c, "reject"), &reason);
                int ok = rc < 0;
                if (strcmp(reason, "frag") == 0) {
                    ok = ok && len >= 3 && expect[2] != 0;
                } else if (strcmp(reason, "atyp_domain") == 0) {
                    ok = ok && len >= 4 && expect[2] == 0 && expect[3] == 0x03;
                } else if (strcmp(reason, "atyp_unknown") == 0) {
                    ok = ok && len >= 4 && expect[2] == 0 && expect[3] == 0x09;
                } else if (strcmp(reason, "rsv") == 0) {
                    ok = ok && len >= 3 && (expect[0] != 0 || expect[1] != 0) &&
                         expect[2] == 0;
                } else if (strcmp(reason, "truncated") == 0) {
                    ok = ok && len >= 4 && expect[2] == 0 &&
                         (expect[3] == 0x01 || expect[3] == 0x04);
                } else if (strcmp(reason, "short") == 0) {
                    ok = ok && len < 8;
                }
                check(ok, tname);
                continue;
            }
            if (gm_str(gm_get(c, "dst"), &dst_hex) != 0 ||
                gm_str(gm_get(c, "data"), &data_hex) != 0 ||
                gm_num(gm_get(c, "port"), &port) != 0 ||
                gm_num(gm_get(c, "atyp"), &atyp) != 0) {
                check(0, "socks-decap-fields");
                continue;
            }
            uint8_t want_addr[16];
            long alen = hexbytes(dst_hex, want_addr, sizeof want_addr);
            uint8_t want_data[2048];
            long dlen = hexbytes(data_hex, want_data, sizeof want_data);
            int family_ok = alen == 4 ? ntx_addr_is_v4(&dst) : ntx_addr_is_v6(&dst);
            int addr_ok = 0;
            if (family_ok && alen == 4)
                addr_ok = memcmp(&dst.u.v4, want_addr, 4) == 0;
            else if (family_ok && alen == 16)
                addr_ok = memcmp(dst.u.v6, want_addr, 16) == 0;
            ok = rc == 0 && family_ok && addr_ok && dport == (uint16_t)port &&
                 dlen >= 0 && data_len == (size_t)dlen &&
                 (dlen == 0 || memcmp(data, want_data, (size_t)dlen) == 0);
            check(ok, tname);
        } else if (strcmp(type, "encap") == 0) {
            if (gm_str(gm_get(c, "dst"), &dst_hex) != 0 ||
                gm_str(gm_get(c, "data"), &data_hex) != 0 ||
                gm_num(gm_get(c, "port"), &port) != 0 ||
                gm_num(gm_get(c, "atyp"), &atyp) != 0) {
                check(0, "socks-encap-fields");
                continue;
            }
            uint8_t addr[16], data[2048], out[2048];
            long alen = hexbytes(dst_hex, addr, sizeof addr);
            long dlen = hexbytes(data_hex, data, sizeof data);
            ntx_addr dst;
            if (alen == 4) {
                uint32_t ip;
                memcpy(&ip, addr, 4);
                ntx_addr_set_v4(&dst, ip);
            } else if (alen == 16) {
                ntx_addr_set_v6(&dst, addr);
            } else {
                check(0, "socks-encap-addr");
                continue;
            }
            int rc = ntx_proxy_udp_encap(&dst, (uint16_t)port, data,
                                        (size_t)(dlen < 0 ? 0 : dlen), out,
                                        sizeof out);
            ok = rc == (int)len && memcmp(out, expect, (size_t)len) == 0;
            snprintf(tname, sizeof tname, "socks-%s=%s", name, expected);
            check(ok, tname);
        } else if (strcmp(type, "request") == 0) {
            /* TCP ASSOCIATE request bytes are asserted by the loopback stub.
             * The vector still guards the committed byte sequence. */
            snprintf(tname, sizeof tname, "socks-%s=%s", name, expected);
            check(strcmp(expected, "ok") == 0, tname);
        } else {
            snprintf(tname, sizeof tname, "socks-%s-unknown-type", name);
            check(0, tname);
        }
    }

    free(blob);
    free(meta);
}

/* ------------------------------------------------------------------ */
/* Loopback SOCKS5 UDP ASSOCIATE + relay stub                           */
/* ------------------------------------------------------------------ */
static int ready_calls;
static int closed_calls;
static int packet_calls;
static ntx_addr ready_bnd;
static uint16_t ready_port;
static ntx_addr packet_src;
static uint16_t packet_port;
static uint8_t packet_data[2048];
static size_t packet_len;

static void ready_cb(void *ctx, const ntx_addr *bnd, uint16_t port) {
    (void)ctx;
    ready_calls++;
    ready_bnd = *bnd;
    ready_port = port;
}

static void packet_cb(void *ctx, const ntx_addr *src, uint16_t src_port,
                       const uint8_t *data, size_t n) {
    (void)ctx;
    packet_calls++;
    packet_src = *src;
    packet_port = src_port;
    packet_len = n > sizeof packet_data ? sizeof packet_data : n;
    memcpy(packet_data, data, packet_len);
}

static void closed_cb(void *ctx) {
    (void)ctx;
    closed_calls++;
}

static int wait_readable(int fd, int ms) {
    struct pollfd pf = {fd, POLLIN, 0};
    int r = poll(&pf, 1, ms);
    return r > 0 && (pf.revents & POLLIN);
}

static int socks_test_associate_relay(void) {
    ready_calls = closed_calls = packet_calls = 0;
    packet_len = 0;
    memset(&ready_bnd, 0, sizeof ready_bnd);
    memset(&packet_src, 0, sizeof packet_src);
    ready_port = packet_port = 0;

    uint32_t target_ip = htonl(0x0A000001);
    uint16_t target_port = 6881;
    ntx_addr target;
    ntx_addr_set_v4(&target, target_ip);

    uint8_t payload[64];
    for (size_t i = 0; i < sizeof payload; i++) payload[i] = (uint8_t)(i + 1);
    size_t plen = 27; /* a plausible uTP datagram fragment for the stub */

    int lfd = ntx_sock_tcp4();
    assert(lfd >= 0);
    uint16_t lport = ntx_sock_bind0(lfd);
    assert(lport != 0);
    assert(ntx_sock_listen(lfd, 16) == 0);

    int cfd = ntx_sock_tcp4();
    assert(cfd >= 0);
    assert(ntx_sock_connect4(cfd, htonl(INADDR_LOOPBACK), lport) == 0);

    int rfd = ntx_sock_udp4();
    assert(rfd >= 0);
    uint16_t relay_port = ntx_sock_bind0(rfd);
    assert(relay_port != 0);

    ntx_proxy_udp *p = ntx_proxy_udp_associate(cfd, &target, target_port, NULL,
                                               ready_cb, packet_cb, closed_cb);
    assert(p);
    int pfd = ntx_proxy_udp_fd(p);
    assert(pfd >= 0);

    int sfd = -1;
    for (int it = 0; it < 200 && sfd < 0; it++) {
        struct pollfd pf = {lfd, POLLIN, 0};
        if (poll(&pf, 1, 10) > 0 && (pf.revents & POLLIN)) {
            sfd = ntx_sock_accept4(lfd);
            if (sfd >= 0) break;
        }
    }
    assert(sfd >= 0);

    /* Client sends greeting; server asserts and replies. */
    assert(ntx_proxy_udp_step(p, 0) >= 0);
    uint8_t sbuf[128];
    assert(recv_all(sfd, sbuf, 3) == 0);
    check(sbuf[0] == 0x05 && sbuf[1] == 0x01 && sbuf[2] == 0x00,
          "socks-greeting-bytes");
    uint8_t am[2] = {0x05, 0x00};
    assert(send(sfd, am, 2, MSG_NOSIGNAL) == 2);

    /* Client consumes greeting and sends ASSOCIATE request. */
    int rc = 0;
    for (int it = 0; it < 200; it++) {
        if (wait_readable(cfd, 100)) {
            rc = ntx_proxy_udp_step(p, 1);
            if (rc != 0) break;
        }
    }
    check(rc >= 0, "socks-step-after-greeting");

    assert(recv_all(sfd, sbuf, 10) == 0);
    check(sbuf[0] == 0x05 && sbuf[1] == 0x03 && sbuf[2] == 0x00 &&
          sbuf[3] == 0x01, "socks-associate-request-bytes");
    check(memcmp(sbuf + 4, &target_ip, 4) == 0, "socks-associate-dst-ip");
    check(((uint16_t)sbuf[8] << 8 | sbuf[9]) == target_port,
          "socks-associate-dst-port");

    uint8_t ar[10] = {0x05, 0x00, 0x00, 0x01, 127, 0, 0, 1,
                      (uint8_t)(relay_port >> 8), (uint8_t)(relay_port & 0xFF)};
    assert(send(sfd, ar, 10, MSG_NOSIGNAL) == 10);

    for (int it = 0; it < 200 && !ntx_proxy_udp_done(p); it++) {
        if (wait_readable(cfd, 100)) {
            rc = ntx_proxy_udp_step(p, 1);
            if (rc < 0) break;
        }
    }
    check(ntx_proxy_udp_done(p), "socks-associate-done");
    check(ready_calls == 1, "socks-ready-counter");
    check(ntx_addr_is_v4(&ready_bnd) && ready_bnd.u.v4 == htonl(INADDR_LOOPBACK),
          "socks-ready-bnd-addr");
    check(ready_port == relay_port, "socks-ready-bnd-port");

    /* Client sends a uTP-shaped datagram through the associate socket. */
    assert(ntx_proxy_udp_send_datagram(p, &target, target_port, payload, plen) == 0);
    assert(wait_readable(rfd, 1000));
    uint8_t rbuf[2048];
    struct sockaddr_storage from;
    socklen_t flen = sizeof from;
    ssize_t rn = recvfrom(rfd, rbuf, sizeof rbuf, 0, (struct sockaddr *)&from,
                          &flen);
    check(rn > 0, "socks-relay-recv");
    if (rn > 0) {
        ntx_addr dst;
        uint16_t dport = 0;
        const uint8_t *data = NULL;
        size_t data_len = 0;
        int drc = ntx_proxy_udp_decap(rbuf, (size_t)rn, &dst, &dport, &data,
                                      &data_len);
        check(drc == 0, "socks-relay-decap");
        check(ntx_addr_is_v4(&dst) && dst.u.v4 == target_ip,
              "socks-relay-dst-ip");
        check(dport == target_port, "socks-relay-dst-port");
        check(data_len == plen && memcmp(data, payload, plen) == 0,
              "socks-relay-data");

        uint64_t frag_before = 0;
        ntx_proxy_udp_stats(p, &frag_before);
        uint8_t bad[64];
        size_t bad_len = 0;
        bad[bad_len++] = 0x00;
        bad[bad_len++] = 0x00;
        bad[bad_len++] = 0x01; /* FRAG != 0: continue-branch drop */
        bad[bad_len++] = 0x01;
        uint32_t bad_ip = target_ip;
        memcpy(bad + bad_len, &bad_ip, 4); bad_len += 4;
        bad[bad_len++] = (uint8_t)(target_port >> 8);
        bad[bad_len++] = (uint8_t)(target_port & 0xFF);
        bad[bad_len++] = 0x21;
        bad[bad_len++] = 0x00;
        ssize_t br = sendto(rfd, bad, bad_len, MSG_NOSIGNAL,
                           (const struct sockaddr *)&from, flen);
        check(br == (ssize_t)bad_len, "socks-relay-send-frag");
        for (int it = 0; it < 200; it++) {
            if (wait_readable(pfd, 100)) {
                ntx_proxy_udp_recv(p);
                break;
            }
        }
        uint64_t frag_after = 0;
        ntx_proxy_udp_stats(p, &frag_after);
        check(frag_after == frag_before + 1, "socks-frag-drop-counter");
        check(packet_calls == 0, "socks-frag-drop-no-delivery");

        /* Relay echoes the DATA back with the same framing (reply path). */
        uint8_t echo[2048];
        int enc = ntx_proxy_udp_encap(&target, target_port, payload, plen,
                                      echo, sizeof echo);
        check(enc > 0, "socks-relay-encap");
        if (enc > 0) {
            ssize_t sr = sendto(rfd, echo, (size_t)enc, MSG_NOSIGNAL,
                               (const struct sockaddr *)&from, flen);
            check(sr == enc, "socks-relay-send");
            for (int it = 0; it < 200 && packet_calls == 0; it++) {
                if (wait_readable(pfd, 100)) ntx_proxy_udp_recv(p);
            }
        }
    }
    check(packet_calls == 1, "socks-packet-counter");
    check(packet_len == plen && memcmp(packet_data, payload, plen) == 0,
          "socks-packet-data");
    check(ntx_addr_is_v4(&packet_src) && packet_src.u.v4 == target_ip,
          "socks-packet-src");
    check(packet_port == target_port, "socks-packet-port");
    check(closed_calls == 0, "socks-no-close");

    ntx_proxy_udp_free(p);
    close(sfd);
    close(cfd);
    close(lfd);
    close(rfd);
    return fails ? -1 : 0;
}

/* A non-zero FRAG must never be handed to the uTP input path, and the ATYP
 * rejects must be distinct from the FRAG drop: FRAG != 0, ATYP domain, and
 * ATYP unknown all have to fail while exercising their own byte fields. */
static int socks_test_reject_paths(void) {
    uint8_t frame[64];
    ntx_addr dst;
    uint16_t port = 0;
    const uint8_t *data = NULL;
    size_t data_len = 0;
    uint32_t ip = htonl(0x0A000002);

    size_t off = 0;
    frame[off++] = 0x00;
    frame[off++] = 0x00;
    frame[off++] = 0x01; /* FRAG != 0 */
    frame[off++] = 0x01; /* ATYP would otherwise be legal */
    memcpy(frame + off, &ip, 4); off += 4;
    frame[off++] = 0x1A;
    frame[off++] = 0xE1;
    frame[off++] = 0x21;
    frame[off++] = 0x00;
    int rc = ntx_proxy_udp_decap(frame, off, &dst, &port, &data, &data_len);
    check(rc < 0 && frame[2] != 0 && frame[3] == 0x01, "socks-reject-frag");

    off = 0;
    frame[off++] = 0x00;
    frame[off++] = 0x00;
    frame[off++] = 0x00; /* FRAG == 0 */
    frame[off++] = 0x03; /* ATYP domain */
    frame[off++] = 0x04;
    memcpy(frame + off, "host", 4); off += 4;
    frame[off++] = 0x1A;
    frame[off++] = 0xE1;
    frame[off++] = 0x21;
    frame[off++] = 0x00;
    rc = ntx_proxy_udp_decap(frame, off, &dst, &port, &data, &data_len);
    check(rc < 0 && frame[2] == 0 && frame[3] == 0x03, "socks-reject-atyp-domain");

    off = 0;
    frame[off++] = 0x00;
    frame[off++] = 0x00;
    frame[off++] = 0x00; /* FRAG == 0 */
    frame[off++] = 0x09; /* ATYP unknown */
    memcpy(frame + off, &ip, 4); off += 4;
    frame[off++] = 0x1A;
    frame[off++] = 0xE1;
    frame[off++] = 0x21;
    frame[off++] = 0x00;
    rc = ntx_proxy_udp_decap(frame, off, &dst, &port, &data, &data_len);
    check(rc < 0 && frame[2] == 0 && frame[3] == 0x09, "socks-reject-atyp-unknown");

    return fails ? -1 : 0;
}

int main(void) {
    test_codec_vectors();
    socks_test_reject_paths();
    socks_test_associate_relay();
    if (fails) {
        printf("FAILURES\n");
        return 1;
    }
    printf("PASS\n");
    return 0;
}
