/* A4: TLS golden-capture replay harness (test/fixtures/tls/).
 *
 * Replays committed TLS 1.3 wire fixtures (generated by the independent Python
 * reference test/scripts/tls13_ref.py) through the SAME parse/verify path
 * the production client uses (ntx_tls_handshake_ex, NTX_TLS13_LIVE) and asserts
 * the expected outcome recorded in the fixture's .meta.json. Deterministic and
 * OFFLINE: no network, client keys are fixed via ntx_tls13_test_set_keys, and
 * the server stream is the frozen .bin capture (not regenerated in-process).
 *
 * Fixture layout:
 *   test/fixtures/tls/<name>.bin        raw server stream (bytes the client reads)
 *   test/fixtures/tls/<name>.meta.json  name/source/date/scrub_notes +
 *                                       client{...} + expected{...}
 *
 * The .bin is replayed as: feed it to the client over a socketpair, run the
 * real 1.3 handshake with the expected leaf pin, then check version / ALPN /
 * leaf pin / app keys / app data, and that the client's own ClientHello hashes
 * to the frozen capture (CH determinism).
 *
 * Runs under `make test` (wildcard test/t_*.c) and `make test-live`.
 */
#define NTX_TLS13_LIVE 1
#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

#include "../src/crypto/ntx_aes.c"
#include "../src/crypto/ntx_bignum.c"
#include "../src/crypto/ntx_hmac.c"
#include "../src/crypto/ntx_hkdf.c"
#include "../src/crypto/ntx_p256.c"
#include "../src/crypto/ntx_rng.c"
#include "../src/crypto/ntx_rsa_pkcs1.c"
#include "../src/crypto/ntx_sha1.c"
#include "../src/crypto/ntx_sha256.c"
#include "../src/crypto/ntx_x25519_fe.c"
#include "../src/crypto/ntx_x25519.c"
#include "../src/net/ntx_tls.c"
#include "../src/net/ntx_tls13.c"
#include "../src/net/ntx_tls_rec.c"
#include "../src/ui/ntx_diag.c"
#include "util.h"

static void fail(const char *name) {
    printf("FAIL %s\n", name);
    exit(1);
}

static void bytes_to_hex(char *dst, const uint8_t *b, size_t n) {
    static const char *H = "0123456789abcdef";
    for (size_t i = 0; i < n; i++) {
        dst[2 * i] = H[b[i] >> 4];
        dst[2 * i + 1] = H[b[i] & 15];
    }
    dst[2 * n] = '\0';
}

/* Minimal JSON scalar extractor (zero deps, C11 + libc only). Finds the first
 * "key" and returns its value: a string (malloc'd; we emit no escapes) or a
 * bare number/literal token. Containers ({/[]) -> NULL. Caller frees. */
static char *json_get(const char *doc, const char *key) {
    char pat[64];
    snprintf(pat, sizeof pat, "\"%s\"", key);
    const char *p = strstr(doc, pat);
    if (!p) return NULL;
    p += strlen(pat);
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p != ':') return NULL;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p == '{' || *p == '[') return NULL;
    char *out;
    if (*p == '"') {
        p++;
        size_t len = 0;
        while (p[len] && p[len] != '"') len++;
        if (!p[len]) return NULL;
        out = malloc(len + 1);
        if (!out) exit(1);
        memcpy(out, p, len);
        out[len] = '\0';
        return out;
    }
    const char *s = p;
    while (*p && *p != ',' && *p != '}' && *p != ']' &&
           *p != '\n' && *p != '\r' && *p != ' ') p++;
    size_t len = (size_t)(p - s);
    if (len == 0) return NULL;
    out = malloc(len + 1);
    if (!out) exit(1);
    memcpy(out, s, len);
    out[len] = '\0';
    return out;
}

/* Locate a top-level object's body (the '{' after "container":). */
static const char *json_object_body(const char *doc, const char *container) {
    char pat[64];
    snprintf(pat, sizeof pat, "\"%s\"", container);
    const char *p = strstr(doc, pat);
    if (!p) return NULL;
    p += strlen(pat);
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    if (*p != ':') return NULL;
    p++;
    while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
    return (*p == '{') ? p : NULL;
}

/* Extract scalar "field" from within the "container" object. */
static char *json_get_in(const char *doc, const char *container,
                         const char *field) {
    const char *body = json_object_body(doc, container);
    if (!body) return NULL;
    const char *end = strchr(body, '}');
    if (!end) return NULL;
    size_t len = (size_t)(end - body);
    char *tmp = malloc(len + 1);
    if (!tmp) exit(1);
    memcpy(tmp, body, len);
    tmp[len] = '\0';
    char *val = json_get(tmp, field);
    free(tmp);
    return val;
}

static int replay(const char *binpath, const char *metapath) {
    size_t sn;
    uint8_t *stream = read_file(binpath, &sn);

    size_t mn;
    uint8_t *metaraw = read_file(metapath, &mn);
    char *meta = malloc(mn + 1);
    if (!meta) exit(1);
    memcpy(meta, metaraw, mn);
    meta[mn] = '\0';

    char *sni = json_get_in(meta, "client", "sni");
    char *alpn_s = json_get_in(meta, "client", "alpn");
    char *priv_hex = json_get_in(meta, "client", "client_priv_hex");
    char *cr_hex = json_get_in(meta, "client", "client_random_hex");
    char *ch_sha = json_get_in(meta, "client", "ch_sha256_hex");
    char *spki_hex = json_get_in(meta, "expected", "spki_sha256_hex");
    char *outcome = json_get_in(meta, "expected", "outcome");
    if (!sni || !priv_hex || !cr_hex || !outcome) fail("meta-missing");

    uint8_t priv[32], cr[32];
    uint8_t pin[32] = { 0 };
    hex_to_bytes(priv_hex, priv, 32);
    hex_to_bytes(cr_hex, cr, 32);
    int npins = 0;
    if (spki_hex) {
        hex_to_bytes(spki_hex, pin, 32);
        npins = 1;
    }

    ntx_tls13_test_set_keys(priv, cr);

    int sv[2];
    if (socketpair(AF_UNIX, SOCK_STREAM, 0, sv) != 0) fail("socketpair");
    size_t off = 0;
    while (off < sn) {
        ssize_t w = write(sv[1], stream + off, sn - off);
        if (w <= 0) fail("stream-write");
        off += (size_t)w;
    }

    const char *alpn_list[1];
    int nalpn = 0;
    if (alpn_s && alpn_s[0]) {
        alpn_list[0] = alpn_s;
        nalpn = 1;
    }

    ntx_tls t;
    ntx_tls_init(&t);
    t.fd = sv[0];
    int rc = ntx_tls_handshake_ex(&t, t.fd, sni, (const uint8_t(*)[32])pin,
                                  npins, 15, alpn_list, nalpn);

    /* CH determinism: the client's ClientHello (first record) must hash to the
       frozen capture — catches any non-determinism in CH generation. */
    if (ch_sha) {
        uint8_t hdr[5];
        if (io_read(sv[1], hdr, 5) != 0 || hdr[0] != 0x16) fail("ch-hdr");
        size_t L = ntx_wire_rd16(hdr + 3);
        uint8_t *chgot = malloc(L ? L : 1);
        if (!chgot) exit(1);
        if (io_read(sv[1], chgot, L) != 0) fail("ch-read");
        uint8_t chd[32];
        ntx_sha256(chgot, L, chd);
        char chd_hex[65];
        bytes_to_hex(chd_hex, chd, 32);
        if (strcmp(chd_hex, ch_sha) != 0) fail("ch-hash");
        free(chgot);
    }

    if (strcmp(outcome, "ok") == 0) {
        if (rc != NTX_TLS_OK) fail("rc-ok");
        char *ver_s = json_get_in(meta, "expected", "tls_version");
        if (!ver_s || t.ver != atoi(ver_s)) fail("ver");
        free(ver_s);
        char *alpn_exp = json_get_in(meta, "expected", "alpn");
        if (alpn_exp && strcmp(t.alpn, alpn_exp) != 0) fail("alpn");
        free(alpn_exp);
        if (!t.leaf_pin_valid) fail("leaf-valid");
        if (npins && memcmp(t.leaf_pin, pin, 32) != 0) fail("leaf-pin");
        char *cs = json_get_in(meta, "expected", "c_ap_secret_hex");
        char *ss = json_get_in(meta, "expected", "s_ap_secret_hex");
        char *cf = json_get_in(meta, "expected", "client_flight_hex");
        char *app = json_get_in(meta, "expected", "app_data_hex");
        if (!cs || !ss || !cf || !app) fail("meta-keys");
        uint8_t cs32[32], ss32[32];
        hex_to_bytes(cs, cs32, 32);
        hex_to_bytes(ss, ss32, 32);
        if (!t.w13.active || !t.r13.active) fail("dirs-active");
        if (memcmp(t.w13.secret, cs32, 32) != 0) fail("client-app-secret");
        if (memcmp(t.r13.secret, ss32, 32) != 0) fail("server-app-secret");
        if (t.w13.seq != 0 || t.r13.seq != 0) fail("seq-reset");
        /* what the client put on the wire after its ClientHello: CCS + Finished */
        size_t cf_n = strlen(cf) / 2;
        if (cf_n > 256) fail("cf-cap");
        uint8_t cf_exp[256], cf_got[256];
        hex_to_bytes(cf, cf_exp, cf_n);
        if (io_read(sv[1], cf_got, cf_n) != 0) fail("cf-read");
        if (memcmp(cf_got, cf_exp, cf_n) != 0) fail("client-flight");
        /* app data after NewSessionTicket + KeyUpdate (padded record), then close_notify */
        size_t app_n = strlen(app) / 2;
        if (app_n > 256) fail("app-cap");
        uint8_t app_exp[256], app_buf[256];
        hex_to_bytes(app, app_exp, app_n);
        ssize_t an = ntx_tls_read(&t, app_buf, sizeof app_buf);
        if (an < 0 || (size_t)an != app_n) fail("app-read");
        if (memcmp(app_buf, app_exp, app_n) != 0) fail("app-data");
        if (ntx_tls_read(&t, app_buf, sizeof app_buf) != 0) fail("close-notify");
        free(cs);
        free(ss);
        free(cf);
        free(app);
    } else if (strcmp(outcome, "pin-fail") == 0) {
        if (rc != NTX_TLS_PIN_FAIL) fail("rc-pinfail");
    } else if (strcmp(outcome, "fail") == 0) {
        if (rc != NTX_TLS_FAIL) fail("rc-fail");
    } else {
        fail("unknown-outcome");
    }

    ntx_tls13_test_clear_keys();
    close(sv[0]);
    close(sv[1]);
    free(sni);
    free(alpn_s);
    free(priv_hex);
    free(cr_hex);
    free(ch_sha);
    free(spki_hex);
    free(outcome);
    free(meta);
    free(metaraw);
    free(stream);
    return 0;
}

static int cmp_names(const void *a, const void *b) {
    return strcmp(*(const char(*)[256])a, *(const char(*)[256])b);
}

int main(void) {
    const char *dir = "test/fixtures/tls";
    DIR *d = opendir(dir);
    if (!d) {
        printf("FAIL open %s: %s\n", dir, strerror(errno));
        return 1;
    }
    char names[64][256];
    int n = 0;
    struct dirent *e;
    while ((e = readdir(d)) != NULL && n < 64) {
        const char *nm = e->d_name;
        size_t l = strlen(nm);
        if (l > 4 && strcmp(nm + l - 4, ".bin") == 0) {
            memcpy(names[n], nm, l - 4);
            names[n][l - 4] = '\0'; /* strip ".bin" */
            n++;
        }
    }
    closedir(d);
    if (n == 0) {
        printf("FAIL no fixtures in %s\n", dir);
        return 1;
    }
    qsort(names, (size_t)n, sizeof names[0], cmp_names);
    size_t dl = strlen(dir);
    for (int i = 0; i < n; i++) {
        size_t nl = strlen(names[i]);
        char binpath[512], metapath[512];
        if (dl + 1 + nl + 4 >= sizeof binpath) fail("path-too-long");
        if (dl + 1 + nl + 11 >= sizeof metapath) fail("path-too-long");
        memcpy(binpath, dir, dl);
        binpath[dl] = '/';
        memcpy(binpath + dl + 1, names[i], nl);
        memcpy(binpath + dl + 1 + nl, ".bin", 5);
        memcpy(metapath, dir, dl);
        metapath[dl] = '/';
        memcpy(metapath + dl + 1, names[i], nl);
        memcpy(metapath + dl + 1 + nl, ".meta.json", 11);
        if (replay(binpath, metapath) != 0) return 1;
        printf("PASS %s\n", names[i]);
    }
    printf("ALL PASS (%d fixture%s)\n", n, n == 1 ? "" : "s");
    return 0;
}
