/* Shared-demux first-byte classifier (ntx_udp_classify).
 * Self-contained TU: loads the committed golden vectors
 * (test/vectors/utp/demux_classify.bin + .meta.json, generated by
 * test/scripts/utp_demux_vectors.py) and asserts every
 * classification, then fuzzes all 256 first bytes at len 1/2 for no-crash. */
#include <arpa/inet.h>
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "golden_meta.h"
#include "../src/net/ntx_addr.c"
#include "../src/net/ntx_netx.c"
#include "../src/net/ntx_sock.c"
#include "../src/net/ntx_proxy.c"
#include "../src/net/ntx_tunnel.c"
#include "../src/ui/ntx_diag.c"
#include "../src/crypto/ntx_aes.c"
#include "../src/crypto/ntx_hmac.c"
#include "../src/crypto/ntx_sha256.c"
#include "../src/crypto/ntx_sha1.c"
#include "../src/crypto/ntx_rng.c"

static int fails;

static void check(int cond, const char *name) {
    if (cond) printf("PASS %s\n", name);
    else { printf("FAIL %s\n", name); fails = 1; }
}

static uint8_t *read_file(const char *path, size_t *n) {
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return NULL; }
    uint8_t *buf = malloc(sz > 0 ? (size_t)sz : 1);
    if (!buf) { fclose(f); return NULL; }
    size_t rd = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    if (rd != (size_t)sz) { free(buf); return NULL; }
    *n = (size_t)sz;
    return buf;
}

static int hexnib(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

/* Decode an even-length hex string. Returns byte count, or -1 on malformed. */
static long hexbytes(const char *hex, uint8_t *out, size_t cap) {
    size_t len = strlen(hex);
    if (len % 2 != 0) return -1;
    if (len / 2 > cap) return -1;
    for (size_t i = 0; i < len / 2; i++) {
        int hi = hexnib(hex[2 * i]), lo = hexnib(hex[2 * i + 1]);
        if (hi < 0 || lo < 0) return -1;
        out[i] = (uint8_t)((hi << 4) | lo);
    }
    return (long)(len / 2);
}

static const char *kind_name(ntx_udp_kind k) {
    switch (k) {
    case NTX_UDP_DHT: return "dht";
    case NTX_UDP_UTP: return "utp";
    case NTX_UDP_DROP: return "drop";
    }
    return "?";
}

static int kind_eq(const char *want, ntx_udp_kind got) {
    return strcmp(want, kind_name(got)) == 0;
}

/* ------------------------------------------------------------------ */
static void test_demux_vectors(void) {
    size_t mn = 0;
    uint8_t *meta = read_file("test/vectors/utp/demux_classify.meta.json", &mn);
    check(meta != NULL, "demux-meta-read");
    if (!meta) return;

    gm root;
    check(gm_parse((const char *)meta, mn, &root) == 0, "demux-meta-parse");
    if (root.t != GM_OBJ) { check(0, "demux-meta-obj"); free(meta); return; }

    const gm *bin = gm_get(&root, "bin");
    const gm *want_sha = gm_get(&root, "bin_sha256");
    const gm *cnt = gm_get(&root, "count");
    const gm *arr = gm_get(&root, "cases");
    int64_t ecnt = -1;
    check(bin && want_sha && cnt && gm_num(cnt, &ecnt) == 0 && arr &&
          arr->t == GM_ARR, "demux-meta-shape");
    if (!bin || !want_sha || !cnt || !arr || arr->t != GM_ARR) {
        free(meta);
        return;
    }

    size_t bn = 0;
    const char *binp = NULL;
    if (gm_str(bin, &binp) != 0 || !binp) {
        check(0, "demux-bin-name");
        free(meta);
        return;
    }
    uint8_t *blob = read_file(binp, &bn);
    check(blob != NULL, "demux-bin-read");
    if (!blob) { free(meta); return; }

    uint8_t dig[32];
    ntx_sha256(blob, bn, dig);
    char dighex[65];
    for (int i = 0; i < 32; i++) sprintf(dighex + 2 * i, "%02x", dig[i]);
    dighex[64] = 0;
    const char *ewant = NULL;
    check(gm_str(want_sha, &ewant) == 0 && strcmp(dighex, ewant) == 0,
          "demux-bin-sha256");

    check((int64_t)arr->ne == ecnt, "demux-case-count");

    for (size_t i = 0; i < arr->ne; i++) {
        const gm *c = arr->el[i];
        if (!c || c->t != GM_OBJ) { check(0, "demux-case-obj"); continue; }
        const char *name = "?", *hex = "", *exp = "?";
        int64_t off = -1, len = -1;
        if (gm_str(gm_get(c, "name"), &name) != 0 ||
            gm_str(gm_get(c, "hex"), &hex) != 0 ||
            gm_str(gm_get(c, "expected"), &exp) != 0 ||
            gm_num(gm_get(c, "off"), &off) != 0 ||
            gm_num(gm_get(c, "len"), &len) != 0) {
            check(0, "demux-case-fields");
            continue;
        }
        uint8_t expect_bytes[256];
        long hn = hexbytes(hex, expect_bytes, sizeof expect_bytes);
        int ok = hn >= 0 && hn == len && off >= 0 &&
                 (size_t)off + (size_t)len <= bn &&
                 (len == 0 || memcmp(blob + off, expect_bytes, (size_t)len) == 0);
        char tname[128];
        snprintf(tname, sizeof tname, "demux-%s-integrity", name);
        check(ok, tname);

        ntx_udp_kind got = ntx_udp_classify(len ? blob + off : NULL,
                                            (size_t)len);
        ok = kind_eq(exp, got);
        snprintf(tname, sizeof tname, "demux-%s=%s", name, exp);
        check(ok, tname);
    }

    free(blob);
    free(meta);
}

/* ------------------------------------------------------------------ */
/* Boundary fuzz: every first byte x at len 1 and len 2 — no crash,
 * always a valid enum value; classification depends only on byte 0. */
static void test_boundary_fuzz(void) {
    int ok = 1;
    for (int x = 0; x < 256; x++) {
        uint8_t b[2];
        b[0] = (uint8_t)x;
        b[1] = (uint8_t)(x ^ 0xA5);
        ntx_udp_kind k1 = ntx_udp_classify(b, 1);
        ntx_udp_kind k2 = ntx_udp_classify(b, 2);
        if (k1 != NTX_UDP_DHT && k1 != NTX_UDP_UTP && k1 != NTX_UDP_DROP)
            ok = 0;
        if (k2 != k1) ok = 0; /* second byte must not change the verdict */
    }
    check(ok, "fuzz-all-256-first-bytes");

    /* Empty / NULL datagrams are the drop class, never a deref. */
    check(ntx_udp_classify(NULL, 0) == NTX_UDP_DROP, "fuzz-null-empty");
    uint8_t z = 0x21;
    check(ntx_udp_classify(&z, 0) == NTX_UDP_DROP, "fuzz-len0-nonnull");

    /* The 0x64/0x6c/0x69 trap bytes are DHT, never uTP. */
    uint8_t d = 0x64, l = 0x6C, i = 0x69;
    check(ntx_udp_classify(&d, 1) == NTX_UDP_DHT &&
          ntx_udp_classify(&l, 1) == NTX_UDP_DHT &&
          ntx_udp_classify(&i, 1) == NTX_UDP_DHT, "trap-64-6c-69-dht");

    /* Legal uTP v1 starts are exactly type 0..4 with ver nibble 1. */
    uint8_t u = 0x41; /* type 4 (SYN), ver 1 */
    uint8_t v = 0x51; /* type 5, ver 1 — illegal */
    uint8_t w = 0x42; /* type 4, ver 2 — illegal */
    check(ntx_udp_classify(&u, 1) == NTX_UDP_UTP &&
          ntx_udp_classify(&v, 1) == NTX_UDP_DROP &&
          ntx_udp_classify(&w, 1) == NTX_UDP_DROP, "utp-nibble-boundary");
}

int main(void) {
    test_demux_vectors();
    test_boundary_fuzz();
    return fails ? 1 : 0;
}
