#!/usr/bin/env python3
"""aes_vectors.py - AES-128-GCM / AES-128-CTR vectors for src/crypto/ntx_aes.c.

Made with the `cryptography` package (OpenSSL), i.e. independent of ntx. Output:
test/vectors/aes/vectors.txt, lines
    gcm <key> <nonce> <aad|-> <pt|-> <ct|-> <tag>
    ctr <key> <ctr0> <pt|-> <ct|->
Lengths straddle every block/word boundary (0, 1, 15, 16, 17, ..., a full 16 KiB TLS record);
CTR counters never carry out of the low 64 bits (ntx_aes128_ctr is a 64-bit-counter CTR).

Run from the repository root:  python3 test/scripts/aes_vectors.py
"""
import os
import random

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def hx(b):
    return b.hex() if b else "-"


def main():
    rnd = random.Random(0xAE5)
    lines = ["# generated by test/scripts/aes_vectors.py - do not edit"]
    pt_lens = [0, 1, 15, 16, 17, 31, 32, 33, 47, 48, 63, 64, 65, 100, 255, 256, 1000, 4096, 16384]
    aad_lens = [0, 1, 13, 16, 17, 33, 64]
    for i, pl in enumerate(pt_lens):
        for al in (aad_lens if pl <= 100 else (0, 13)):
            key, nonce = rnd.randbytes(16), rnd.randbytes(12)
            aad, pt = rnd.randbytes(al), rnd.randbytes(pl)
            out = AESGCM(key).encrypt(nonce, pt, aad if aad else None)
            lines.append("gcm %s %s %s %s %s %s" % (key.hex(), nonce.hex(), hx(aad), hx(pt), hx(out[:-16]), out[-16:].hex()))
    for pl in (0, 1, 15, 16, 17, 33, 64, 100, 1000, 4096):
        key = rnd.randbytes(16)
        ctr0 = rnd.randbytes(8) + (rnd.getrandbits(32)).to_bytes(4, "big") + b"\x00" * 4  # far from a 64-bit carry
        pt = rnd.randbytes(pl)
        enc = Cipher(algorithms.AES(key), modes.CTR(ctr0)).encryptor()
        ct = enc.update(pt) + enc.finalize()
        lines.append("ctr %s %s %s %s" % (key.hex(), ctr0.hex(), hx(pt), hx(ct)))

    out = os.path.join(ROOT, "test", "vectors", "aes")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "vectors.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d vectors" % (len(lines) - 1))


if __name__ == "__main__":
    main()
