#!/usr/bin/env python3
"""bignum_vectors.py - known-answer vectors for src/crypto/ntx_bignum.c.

Writes test/vectors/bignum/vectors.txt. Every line is
    modexp <nbytes> <base> <exp> <mod> <result>
    mulmod <nbytes> <a> <b> <mod> <result>
    mod    <nbytes> <a> <mod> <result>
    reject <nbytes> <mod>      (modulus the Montgomery core must refuse: even, 0, 1, 2;
                                every operation must then return all zero bytes - fail closed)
(all hex, big-endian; base/a/b/mod/result are exactly <nbytes> bytes, exp has its own
length), computed with Python's pow()/% - code that shares nothing with ntx.

The set deliberately includes odd moduli, rejected (even / tiny) moduli, moduli with leading zero bytes,
bases that are >= the modulus, exponent 0, and the real P-256 p/n and a 4096-bit modulus.

Run from the repository root:  python3 test/scripts/bignum_vectors.py
"""
import os
import random

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
P256_P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
P256_N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551


def h(x, n):
    return x.to_bytes(n, "big").hex()


def main():
    rnd = random.Random(0x6E7478)  # fixed seed: the committed file is reproducible
    lines = ["# generated by test/scripts/bignum_vectors.py - do not edit"]

    def modexp(n, base, e, elen, m):
        lines.append("modexp %d %s %s %s %s" % (n, h(base, n), h(e, elen), h(m, n), h(pow(base, e, m), n)))

    def mulmod(n, a, b, m):
        lines.append("mulmod %d %s %s %s %s" % (n, h(a, n), h(b, n), h(m, n), h(a * b % m, n)))

    def mod(n, a, m):
        lines.append("mod %d %s %s %s" % (n, h(a, n), h(m, n), h(a % m, n)))

    def rbits(bits):
        return rnd.getrandbits(bits)

    # ---- real moduli: P-256 field / group order, 4096-bit odd modulus ----
    for m in (P256_P, P256_N):
        for _ in range(6):
            a, b = rbits(256) % m, rbits(256) % m
            mulmod(32, a, b, m)
            mod(32, rbits(256), m)
            modexp(32, a, rbits(256), 32, m)
        modexp(32, P256_P - 1, P256_P - 2, 32, m)
        mulmod(32, m - 1, m - 1, m)
        mulmod(32, 0, 5, m)
    # ---- random odd moduli with the top bit set (RSA / DH shaped) ----
    for n in (32, 64, 96, 128, 256, 512):
        for _ in range(4):
            m = rbits(8 * n) | (1 << (8 * n - 1)) | 1
            base = rbits(8 * n)  # may be >= m on purpose (modexp reduces it)
            for elen, e in ((1, 0), (1, 1), (1, 0xC7), (3, 65537), (20, rbits(160))) + (((min(n, 64), rbits(8 * min(n, 64))),) if n <= 128 else ()):
                modexp(n, base, e, elen, m)
            a, b = rbits(8 * n) % m, rbits(8 * n) % m
            mulmod(n, a, b, m)
            mulmod(n, m - 1, m - 1, m)
            mod(n, rbits(8 * n), m)
            mod(n, m, m)
            mod(n, m - 1, m)
    # ---- odd moduli shorter than the buffer (leading zero bytes) ----
    for n, mbits in ((64, 200), (64, 257), (96, 33), (128, 1000), (32, 9)):
        m = rbits(mbits) | (1 << (mbits - 1)) | 1
        modexp(n, rbits(8 * n), rbits(64), 8, m)
        a, b = rbits(mbits) % m, rbits(mbits) % m
        mulmod(n, a, b, m)
        mod(n, rbits(8 * n), m)
    # ---- tiny odd moduli ----
    for m in (3, 5, 65537, 0xFFFFFFFF, 0x100000001):
        modexp(32, rbits(256), rbits(40), 5, m)
        mulmod(32, rbits(256) % m, rbits(256) % m, m)
    # ---- operands >= modulus (mulmod / mod must reduce them first) ----
    for n in (32, 128, 256):
        m = rbits(8 * n) | (1 << (8 * n - 1)) | 1
        for _ in range(3):
            mulmod(n, rbits(8 * n), rbits(8 * n), m)
        mulmod(n, (1 << (8 * n)) - 1, (1 << (8 * n)) - 1, m)
        mulmod(n, m, m, m)
        mulmod(n, m + 1 if m + 1 < (1 << (8 * n)) else m - 1, 3, m)
    # ---- moduli the core refuses: even, zero, one, two (never used by RSA/ECDSA/DH) ----
    for n in (32, 96, 256):
        m = (rbits(8 * n) | (1 << (8 * n - 1))) & ~1
        lines.append("reject %d %s" % (n, h(m, n)))
    lines.append("reject 32 " + h(1 << 255, 32))   # power of two
    lines.append("reject 32 " + h(0, 32))
    lines.append("reject 32 " + h(1, 32))
    lines.append("reject 32 " + h(2, 32))
    lines.append("reject 64 " + h((1 << 200), 64))

    out = os.path.join(ROOT, "test", "vectors", "bignum")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "vectors.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d vectors" % (len(lines) - 1))


if __name__ == "__main__":
    main()
