#!/usr/bin/env python3
"""dh_kat.py - independent known-answer vectors for src/crypto/ntx_dh.c.

Writes test/vectors/dh/kat.txt. Every line is
    <exponent hex> <base hex (96 B)> <base^exponent mod p hex (96 B)>
computed with Python's pow(), i.e. with code that shares nothing with ntx.

It also checks the modulus: 768-bit safe prime from the BitTorrent MSE/PE
specification (generator 2). Its upper 704 bits are those of the Oakley Group 1
prime of RFC 2409 sec. 6.1 (2^768 - 2^704 - 1 + 2^64 * (floor(2^638 * pi) + 149686));
the low 64 bits are the MSE-specific 0x0000000000090563.

Run from the repository root:  python3 test/scripts/dh_kat.py
"""
import os
import random
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
P_HEX = ("ffffffffffffffffc90fdaa22168c234c4c6628b80dc1cd129024e088a67cc74"
         "020bbea63b139b22514a08798e3404ddef9519b3cd3a431b302b0a6df25f1437"
         "4fe1356d6d51c245e485b576625e7ec6f44c42e9a63a36210000000000090563")
P = int(P_HEX, 16)
KEYLEN = 96


def arctan_inv(x, one):
    total = term = one // x
    x2, n, sign = x * x, 1, -1
    while term:
        term //= x2
        n += 2
        total += sign * (term // n)
        sign = -sign
    return total


def floor_pi_2pow(bits):
    one = 1 << (bits + 64)
    return (4 * (4 * arctan_inv(5, one) - arctan_inv(239, one))) >> 64


def miller_rabin(n, rounds=40):
    d, s = n - 1, 0
    while d % 2 == 0:
        d //= 2
        s += 1
    rng = random.Random(1)
    for _ in range(rounds):
        a = rng.randrange(2, n - 2)
        x = pow(a, d, n)
        if x in (1, n - 1):
            continue
        for _ in range(s - 1):
            x = x * x % n
            if x == n - 1:
                break
        else:
            return False
    return True


def check_modulus():
    # 1. matches the C source
    src = open(os.path.join(ROOT, "src/crypto/ntx_dh.c")).read()
    m = re.search(r"ntx_dh_prime\[NTX_DH_KEY_LEN\] = \{(.*?)\};", src, re.S)
    code = bytes(int(h, 16) for h in re.findall(r"0x([0-9a-f]{2})", m.group(1)))
    assert int.from_bytes(code, "big") == P, "ntx_dh.c prime differs from the spec value"
    # 2. upper 704 bits follow the Oakley-1 construction
    expect_mid = floor_pi_2pow(638) + 149686
    mid = (P + 1 - (1 << 768) + (1 << 704)) >> 64
    assert mid == expect_mid, "upper bits are not the Oakley-1 construction"
    assert P & ((1 << 64) - 1) == 0x0000000000090563
    # 3. safe prime
    assert miller_rabin(P) and miller_rabin((P - 1) // 2), "modulus is not a safe prime"
    print("modulus OK: 768-bit safe prime, Oakley-1 upper bits, MSE low bits")


def be(n, size):
    return n.to_bytes(size, "big").hex()


def main():
    check_modulus()
    rng = random.Random(0x4e545844)  # fixed seed -> reproducible file
    rows = []
    # edge exponents (20 bytes = what ntx uses for DH secrets)
    for e in (0, 1, 2, (1 << 160) - 1, 1 << 159, 0xDEADBEEF):
        for base in (2, P - 2, 3):
            rows.append((e, base))
    # base 1 and p-1 are rejected by the protocol check, but modexp itself must be right
    rows.append((12345, 1))
    rows.append((12345, P - 1))
    rows.append((12346, P - 1))
    # random pairs
    for _ in range(64):
        rows.append((rng.getrandbits(160), rng.randrange(2, P - 1)))
    # a complete key exchange: A = 2^a, B = 2^b, S = B^a = A^b
    a, b = rng.getrandbits(160), rng.getrandbits(160)
    A, B = pow(2, a, P), pow(2, b, P)
    rows.append((a, 2))
    rows.append((b, 2))
    rows.append((a, B))
    rows.append((b, A))
    assert pow(B, a, P) == pow(A, b, P)

    out = os.path.join(ROOT, "test/vectors/dh/kat.txt")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("# exponent(20B) base(96B) result(96B) - generated by test/scripts/dh_kat.py\n")
        for e, base in rows:
            f.write("%s %s %s\n" % (be(e, 20), be(base, KEYLEN), be(pow(base, e, P), KEYLEN)))
    print("wrote %d vectors to %s" % (len(rows), os.path.relpath(out, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
