#!/usr/bin/env python3
"""mac_vectors.py - HMAC-SHA1/-SHA256, HKDF-Expand and TLS 1.2 PRF vectors.

Computed with Python's hmac/hashlib (stdlib), independent of ntx. Output:
test/vectors/mac/vectors.txt, lines
    hmac1   <key|-> <msg|-> <mac>
    hmac256 <key|-> <msg|-> <mac>
    hkdf    <prk> <info|-> <L> <okm>          (HKDF-Expand, RFC 5869, up to 255*32 bytes)
    prf     <secret> <label> <seed> <L> <out> (TLS 1.2 PRF, P_SHA256, RFC 5246 sec. 5)
"-" stands for the empty string. Key lengths straddle the 64-byte block size.

Run from the repository root:  python3 test/scripts/mac_vectors.py
"""
import hashlib
import hmac
import os
import random

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def hx(b):
    return b.hex() if b else "-"


def hkdf_expand(prk, info, length):
    out, t, i = b"", b"", 1
    while len(out) < length:
        t = hmac.new(prk, t + info + bytes([i]), hashlib.sha256).digest()
        out += t
        i += 1
    return out[:length]


def prf(secret, label, seed, length):
    ls = label + seed
    a = ls
    out = b""
    while len(out) < length:
        a = hmac.new(secret, a, hashlib.sha256).digest()
        out += hmac.new(secret, a + ls, hashlib.sha256).digest()
    return out[:length]


def main():
    rnd = random.Random(0x4D4143)
    lines = ["# generated by test/scripts/mac_vectors.py - do not edit"]
    for klen in (0, 1, 20, 32, 63, 64, 65, 100, 200):
        for mlen in (0, 1, 55, 56, 63, 64, 65, 119, 120, 1000):
            key, msg = rnd.randbytes(klen), rnd.randbytes(mlen)
            lines.append("hmac1 %s %s %s" % (hx(key), hx(msg), hmac.new(key, msg, hashlib.sha1).hexdigest()))
            lines.append("hmac256 %s %s %s" % (hx(key), hx(msg), hmac.new(key, msg, hashlib.sha256).hexdigest()))
    for length in (1, 31, 32, 33, 42, 64, 100, 101, 255, 1000, 4096, 255 * 32):
        for ilen in (0, 1, 10, 100, 300):
            prk, info = rnd.randbytes(32), rnd.randbytes(ilen)
            lines.append("hkdf %s %s %d %s" % (prk.hex(), hx(info), length, hkdf_expand(prk, info, length).hex()))
    for length in (1, 12, 32, 33, 48, 100, 104, 200):
        for label, slen in ((b"master secret", 64), (b"key expansion", 64), (b"client finished", 32),
                            (b"extended master secret", 32), (b"a-label-that-is-quite-long-" * 3, 150), (b"x", 300)):
            secret, seed = rnd.randbytes(rnd.choice((32, 48, 80))), rnd.randbytes(slen)
            lines.append("prf %s %s %s %d %s" % (secret.hex(), label.hex(), seed.hex(), length,
                                                 prf(secret, label, seed, length).hex()))

    out = os.path.join(ROOT, "test", "vectors", "mac")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "vectors.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d vectors" % (len(lines) - 1))


if __name__ == "__main__":
    main()
