#!/usr/bin/env python3
"""p256_vectors.py - ECDSA P-256 / SPKI vectors for src/crypto/ntx_p256.c.

Signatures and keys come from the `cryptography` package (OpenSSL), i.e. an
implementation independent of ntx. Writes test/vectors/p256/vectors.txt:
    ecdsa <qx> <qy> <hash> <r> <s> <1|0> <label>
    spki  <der hex> <1|0> <label>          (1 = must parse as a P-256 key)

Run from the repository root:  python3 test/scripts/p256_vectors.py
(Keys are generated fresh each run; the committed file is one sample.)
"""
import hashlib
import os

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, utils

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
N = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
P = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF


def b32(x):
    return x.to_bytes(32, "big").hex()


def spki_der(pub):
    return pub.public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)


def main():
    lines = ["# generated by test/scripts/p256_vectors.py - do not edit"]
    keys = [ec.generate_private_key(ec.SECP256R1()) for _ in range(8)]
    for ki, key in enumerate(keys):
        nums = key.public_key().public_numbers()
        qx, qy = nums.x, nums.y
        for mi in range(5):
            msg = os.urandom(1 + 17 * mi)
            h = hashlib.sha256(msg).digest()
            der = key.sign(msg, ec.ECDSA(hashes.SHA256()))
            r, s = utils.decode_dss_signature(der)
            hx = h.hex()
            lines.append("ecdsa %s %s %s %s %s 1 ok" % (b32(qx), b32(qy), hx, b32(r), b32(s)))
            lines.append("ecdsa %s %s %s %s %s 1 high-s-form" % (b32(qx), b32(qy), hx, b32(r), b32(N - s)))
            bad = bytearray(h)
            bad[mi % 32] ^= 1 << (mi % 8)
            lines.append("ecdsa %s %s %s %s %s 0 bad-hash" % (b32(qx), b32(qy), bad.hex(), b32(r), b32(s)))
            lines.append("ecdsa %s %s %s %s %s 0 r+1" % (b32(qx), b32(qy), hx, b32((r + 1) % N), b32(s)))
            lines.append("ecdsa %s %s %s %s %s 0 s+1" % (b32(qx), b32(qy), hx, b32(r), b32((s + 1) % N)))
            lines.append("ecdsa %s %s %s %s %s 0 r=0" % (b32(qx), b32(qy), hx, b32(0), b32(s)))
            lines.append("ecdsa %s %s %s %s %s 0 s=0" % (b32(qx), b32(qy), hx, b32(r), b32(0)))
            lines.append("ecdsa %s %s %s %s %s 0 r=n" % (b32(qx), b32(qy), hx, b32(N), b32(s)))
            lines.append("ecdsa %s %s %s %s %s 0 s=n" % (b32(qx), b32(qy), hx, b32(r), b32(N)))
            other = keys[(ki + 1) % len(keys)].public_key().public_numbers()
            lines.append("ecdsa %s %s %s %s %s 0 wrong-key" % (b32(other.x), b32(other.y), hx, b32(r), b32(s)))
        # off-curve / out-of-range keys must be rejected even with a signature that "fits"
        lines.append("ecdsa %s %s %s %s %s 0 off-curve" % (b32(qx), b32(qy ^ 1), h.hex(), b32(r), b32(s)))
        lines.append("ecdsa %s %s %s %s %s 0 x=p" % (b32(P), b32(qy), h.hex(), b32(r), b32(s)))

    # ---- SPKI parsing ----
    good = spki_der(keys[0].public_key())
    lines.append("spki %s 1 p256" % good.hex())
    for curve, label in ((ec.SECP384R1(), "p384"), (ec.SECP256K1(), "secp256k1"), (ec.SECP224R1(), "p224")):
        k = ec.generate_private_key(curve)
        lines.append("spki %s 0 %s" % (spki_der(k.public_key()).hex(), label))
    # id-ecPublicKey replaced by another OID of the same length (1.2.840.10045.2.2 / .3)
    wrong_oid = good.replace(bytes.fromhex("2a8648ce3d0201"), bytes.fromhex("2a8648ce3d0202"), 1)
    lines.append("spki %s 0 wrong-alg-oid" % wrong_oid.hex())
    wrong_curve = good.replace(bytes.fromhex("2a8648ce3d030107"), bytes.fromhex("2a8648ce3d030106"), 1)
    lines.append("spki %s 0 wrong-curve-oid" % wrong_curve.hex())
    # compressed point (0x02/0x03 prefix, 33 bytes) is not supported
    comp = keys[0].public_key().public_bytes(serialization.Encoding.X962, serialization.PublicFormat.CompressedPoint)
    hdr = good[: len(good) - 66]
    comp_spki = bytearray(hdr[:-1] + bytes([0x22]) + b"\x00" + comp)
    comp_spki[1] = len(comp_spki) - 2
    lines.append("spki %s 0 compressed-point" % bytes(comp_spki).hex())
    # trailing garbage inside the outer SEQUENCE
    t = bytearray(good + b"\x05\x00")
    t[1] += 2
    lines.append("spki %s 0 trailing-bytes" % bytes(t).hex())
    # BIT STRING with non-zero unused-bits octet
    ub = bytearray(good)
    ub[len(good) - 66] = 0x01
    lines.append("spki %s 0 unused-bits" % bytes(ub).hex())
    # truncated
    lines.append("spki %s 0 truncated" % good[:-1].hex())

    out = os.path.join(ROOT, "test", "vectors", "p256")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "vectors.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d vectors" % (len(lines) - 1))


if __name__ == "__main__":
    main()
