#!/usr/bin/env python3
"""rsa_pss_vectors.py - RSASSA-PSS (SHA-256, MGF1-SHA256, salt 32) vectors for
src/crypto/ntx_rsa_pkcs1.c:ntx_rsa_pss_verify_sha256.

Signatures are produced by the `cryptography` package (OpenSSL), i.e. an
implementation independent of ntx. Output: test/vectors/rsa_pss/vectors.txt, lines
    <n hex> <e hex> <mhash hex> <sig hex> <expected 1|0> <label>

Run from the repository root:  python3 test/scripts/rsa_pss_vectors.py
(Keys are generated fresh each run; the committed file is just one sample.)
"""
import hashlib
import os
import sys

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def sign(key, msg):
    return key.sign(
        msg,
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=32),
        hashes.SHA256(),
    )


def main():
    lines = []
    for bits in (2048, 2047, 3072):  # 2047: emLen = k-1 path (modBits % 8 == 7)
        key = rsa.generate_private_key(public_exponent=65537, key_size=bits)
        nums = key.public_key().public_numbers()
        k = (nums.n.bit_length() + 7) // 8
        n_hex = nums.n.to_bytes(k, "big").hex()
        e_hex = nums.e.to_bytes(3, "big").hex()
        for i in range(3):
            msg = b"ntx rsa-pss vector %d/%d" % (bits, i)
            mh = hashlib.sha256(msg).digest()
            sig = sign(key, msg)
            assert len(sig) == k
            lines.append((n_hex, e_hex, mh.hex(), sig.hex(), 1, "valid-%d-%d" % (bits, i)))
            if i == 0:
                bad = bytearray(sig)
                bad[len(bad) // 2] ^= 0x01
                lines.append((n_hex, e_hex, mh.hex(), bytes(bad).hex(), 0, "flipped-sig-%d" % bits))
                badh = bytearray(mh)
                badh[0] ^= 0x80
                lines.append((n_hex, e_hex, bytes(badh).hex(), sig.hex(), 0, "wrong-hash-%d" % bits))
                lines.append((n_hex, e_hex, mh.hex(), (b"\x00" * k).hex(), 0, "zero-sig-%d" % bits))
                lines.append((n_hex, e_hex, mh.hex(), n_hex, 0, "sig-eq-n-%d" % bits))
    out = os.path.join(ROOT, "test/vectors/rsa_pss/vectors.txt")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("# n e mhash sig expected label - generated by test/scripts/rsa_pss_vectors.py\n")
        for row in lines:
            f.write("%s %s %s %s %d %s\n" % row)
    print("wrote %d vectors to %s" % (len(lines), os.path.relpath(out, ROOT)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
