#!/usr/bin/env python3
"""rsa_pkcs1_vectors.py - RSASSA-PKCS1-v1_5 (SHA-256) vectors for
src/crypto/ntx_rsa_pkcs1.c:ntx_rsa_pkcs1_verify_sha256.

Signatures come from the `cryptography` package (OpenSSL). Output:
test/vectors/rsa_pkcs1/vectors.txt, lines
    <n hex> <e hex> <digest hex> <sig hex> <expected 1|0> <label>

Besides valid signatures for 1024..4096-bit keys it holds tampered ones and the classic
degenerate-key forgeries (e = 1, e = 0, even e, even modulus) where the "signature" is
just the encoded message and plain textbook arithmetic would accept it.

Run from the repository root:  python3 test/scripts/rsa_pkcs1_vectors.py
"""
import hashlib
import os

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding, rsa

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
PREFIX_SHA256 = bytes.fromhex("3031300d060960864801650304020105000420")


def emsa(digest, k):
    t = PREFIX_SHA256 + digest
    return b"\x00\x01" + b"\xff" * (k - len(t) - 3) + b"\x00" + t


def main():
    lines = ["# generated by test/scripts/rsa_pkcs1_vectors.py - do not edit"]

    def add(n, e, digest, sig, want, label):
        k = (n.bit_length() + 7) // 8
        if isinstance(sig, int):
            sig = sig.to_bytes(k, "big")
        ehex = e.to_bytes(max(1, (e.bit_length() + 7) // 8), "big").hex()
        lines.append("%s %s %s %s %d %s" % (n.to_bytes(k, "big").hex(), ehex, digest.hex(), sig.hex(), want, label))

    for bits in (1024, 2048, 3072, 4096):
        key = rsa.generate_private_key(public_exponent=65537, key_size=bits)
        nums = key.public_key().public_numbers()
        n, e = nums.n, nums.e
        k = bits // 8
        for i in range(3):
            msg = os.urandom(10 + i * 40)
            dg = hashlib.sha256(msg).digest()
            sig = key.sign(msg, padding.PKCS1v15(), hashes.SHA256())
            add(n, e, dg, sig, 1, "ok-%d" % bits)
            bad = bytearray(dg)
            bad[i] ^= 0x80
            add(n, e, bytes(bad), sig, 0, "bad-digest")
            s2 = bytearray(sig)
            s2[(len(s2) // 2) ^ i] ^= 0x01
            add(n, e, dg, bytes(s2), 0, "bad-sig")
        add(n, e, dg, n, 0, "sig=n")
        add(n, e, dg, n + 1, 0, "sig=n+1")
        # a signature over SHA-384 must not verify as SHA-256
        msg = os.urandom(32)
        add(n, e, hashlib.sha256(msg).digest(), key.sign(msg, padding.PKCS1v15(), hashes.SHA384()), 0, "sha384-sig")
        # degenerate public exponents: with e = 1 the encoded message *is* a valid "signature"
        dg = hashlib.sha256(b"structure").digest()
        add(n, 1, dg, emsa(dg, k), 0, "e=1-forgery")
        add(n, 0, dg, emsa(dg, k), 0, "e=0")
        add(n, 2, dg, emsa(dg, k), 0, "e=2")
        add(n - 1, 1, dg, emsa(dg, k), 0, "even-n-e=1")
        add(n - 1, 65537, dg, emsa(dg, k), 0, "even-n")

    out = os.path.join(ROOT, "test", "vectors", "rsa_pkcs1")
    os.makedirs(out, exist_ok=True)
    with open(os.path.join(out, "vectors.txt"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %d vectors" % (len(lines) - 1))


if __name__ == "__main__":
    main()
